kind: pipeline
name: CI/CD for UI

clone:
  depth: 50

steps:
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: node:10.15.1
    volumes:
    - name: cache
      path: /tmp/cache
    commands:
      - cd app
      - npm install
      - npm run build

  - name: publish image
    image: plugins/docker:17.12
    settings:
      repo: lotteryjs/ui-ten-minutes
      auto_tag: true
      dockerfile: Dockerfile.UI
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
        
  - name: update docker-compose
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      target: /data/wwwroot/ten-minutes
      source: docker-compose.UI.yml

  - name: restart
    image: appleboy/drone-ssh
    pull: true
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      script:
        - cd /data/wwwroot/ten-minutes
        - docker-compose -f docker-compose.UI.yml pull ui-ten-minutes
        - docker-compose -f docker-compose.UI.yml up -d --force-recreate --no-deps ui-ten-minutes
        - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f


volumes:
- name: cache
  temp: {}

trigger:
  event:
    - tag

---

kind: pipeline
name: CI/CD for API

clone:
  depth: 50

steps:
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: golang:1.12
    pull: true
    commands:
      - export LD_FLAGS="-w -s -X main.Version=$(git describe --tags | cut -c 2-) -X main.BuildDate=$(date "+%F-%T") -X main.Commit=$(git rev-parse --verify HEAD) -X main.Mode=prod"
      - make build_linux_amd64

  - name: publish image
    image: plugins/docker:17.12
    settings:
      repo: lotteryjs/api-ten-minutes
      auto_tag: true
      dockerfile: Dockerfile.API
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
        
  - name: update docker-compose
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      target: /data/wwwroot/tenapi
      source: docker-compose.API.yml

  - name: restart
    image: appleboy/drone-ssh
    pull: true
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      script:
        - cd /data/wwwroot/tenapi
        - docker-compose -f docker-compose.API.yml pull api-ten-minutes
        - docker-compose -f docker-compose.API.yml up -d --force-recreate --no-deps api-ten-minutes
        - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
  
trigger:
  event:
    - tag
