# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  port: 6868 # the port the HTTP server will listen on
  
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Headers: "content-type"
    Access-Control-Allow-Methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
    Access-Control-Allow-Origin: "https://ten-minutes.lotteryjs.com"
    Access-Control-Expose-Headers: "X-Total-Count"

database: # for database see (configure database section)
  dbname: users_db
  connection: mongodb://127.0.0.1:27017

